package bxms.formmodeler_migration;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Address implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String street;
   private int number;

   public Address()
   {
   }

   public java.lang.String getStreet()
   {
      return this.street;
   }

   public void setStreet(java.lang.String street)
   {
      this.street = street;
   }

   public int getNumber()
   {
      return this.number;
   }

   public void setNumber(int number)
   {
      this.number = number;
   }

   public Address(java.lang.String street, int number)
   {
      this.street = street;
      this.number = number;
   }

}