package bxms.formmodeler_migration;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private int age;
   private java.lang.Boolean married;
   private java.math.BigDecimal salary;
   private java.lang.Integer department;
   @org.kie.api.definition.type.Label("date of birth")
   private java.util.Date birthdate;
   private java.lang.Character sex;
   private java.lang.Double radio;

   private bxms.formmodeler_migration.Address address;

   public Person()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public int getAge()
   {
      return this.age;
   }

   public void setAge(int age)
   {
      this.age = age;
   }

   public java.lang.Boolean getMarried()
   {
      return this.married;
   }

   public void setMarried(java.lang.Boolean married)
   {
      this.married = married;
   }

   public java.math.BigDecimal getSalary()
   {
      return this.salary;
   }

   public void setSalary(java.math.BigDecimal salary)
   {
      this.salary = salary;
   }

   public java.lang.Integer getDepartment()
   {
      return this.department;
   }

   public void setDepartment(java.lang.Integer department)
   {
      this.department = department;
   }

   public java.util.Date getBirthdate()
   {
      return this.birthdate;
   }

   public void setBirthdate(java.util.Date birthdate)
   {
      this.birthdate = birthdate;
   }

   public java.lang.Character getSex()
   {
      return this.sex;
   }

   public void setSex(java.lang.Character sex)
   {
      this.sex = sex;
   }

   public java.lang.Double getRadio()
   {
      return this.radio;
   }

   public void setRadio(java.lang.Double radio)
   {
      this.radio = radio;
   }

   public bxms.formmodeler_migration.Address getAddress()
   {
      return this.address;
   }

   public void setAddress(bxms.formmodeler_migration.Address address)
   {
      this.address = address;
   }

   public Person(java.lang.String name, int age, java.lang.Boolean married,
         java.math.BigDecimal salary, java.lang.Integer department,
         java.util.Date birthdate, java.lang.Character sex,
         java.lang.Double radio, bxms.formmodeler_migration.Address address)
   {
      this.name = name;
      this.age = age;
      this.married = married;
      this.salary = salary;
      this.department = department;
      this.birthdate = birthdate;
      this.sex = sex;
      this.radio = radio;
      this.address = address;
   }

}